// ChromelyMvcVueDemo/vueapp/src/Demo.vue
<template>
  <div>
    <div class="col-12">
        <div class="centerBlock">
            <div class="row">
               <div class="col">
                    <img src="./assets/img/chromely.png" class="img-rounded" alt="Chromely Logo" width="120" height="120" style='margin-top: 20px;' />
               </div>
               <div class="col">
                    <img src="./assets/img/logo.png" class="img-rounded" alt="Vue Logo" width="120" height="120" style='margin-top: 20px;' />
               </div>
            </div>
            <div class="row centerBlock">
                <span class="text-primary text-center"><h2>demo panel</h2></span>
            </div>
        </div>
    </div>

    <div class="col-12">
      <div>
        <router-link to="/"> <button id="buttonDemoRun" type="button" class="btn btn-link" style='margin: 5px;'>Back</button></router-link>
      </div>
      <div class="centerBlock">
        <button v-b-modal.boundJsObjectModal type="button" class="btn btn-light" style='margin: 5px;'>RegisterAsyncJsObject Demo</button>
        <a href="https://github.com/mattkol/Chromely" class="btn btn-default" role="button" style='margin: 5px;'>more info</a>
      </div>
    </div>

    <br>

    <div id="infoPanel" class="col-12 centerBlock">

      <div>
        <div class="card-header card bg-primary text-white">Chromely Main objective</div>
        <div class="card-body"> {{info.Objective}}  </div>
      </div>
      <br>

      <div>
        <div class="card-header card bg-primary text-white">Platforms</div>
        <div class="card-body"> {{info.Platform}} </div>
      </div>
      <br>

      <div>
        <div class="card-header card bg-primary text-white">Current CefSharp/Chromium Version</div>
        <div class="card-body"> {{info.Version}} </div>
      </div>
      <br>

    </div>

    <!-- Bounds Object Modal -->
    <b-modal id="boundJsObjectModal" size="lg" title=".NET/JavaScript Integration (RegisterAsyncJsObject) Demo">
        <b-tabs pills>
            <b-tab title="Get1" active>
              <div class="row">
                <div class="col-12">
                    Route Path:&ensp;/demo/movies &ensp; (Restful Service in Local Assembly)&ensp;<button type="button" class="btn btn-primary btn-sm" v-on:click="boundObjectGet1Click()">Run</button>
                </div>
                <br><br>
                <div class="col-12">
                    <div class='table-responsive'>
                        <table id="boundObjectResult1" class='table'>
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Title</th>
                                    <th>Year</th>
                                    <th>Votes</th>
                                    <th>Rating</th>
                                    <th>Date</th>
                                    <th>RestfulAssembly</th>
                                </tr>
                            </thead>
                            <tbody tr v-for="item in boundObjectGet1Result">
                                <tr>
                                    <th>{{ item.Id }}</th>
                                    <th>{{ item.Title }}</th>
                                    <th>{{ item.Year }}</th>
                                    <th>{{ item.Votes }}</th>
                                    <th>{{ item.Rating }}</th>
                                    <th>{{ item.Date }}</th>
                                    <th>{{ item.RestfulAssembly }}</th>
                                </tr>
                            </tbody>
                       </table>
                    </div>
                </div>
              </div>
            </b-tab>
            <b-tab title="Get2">
              <div class="row">
                <div class="col-12">
                    Route Path:&ensp;/external/movies &ensp; (Restful Service in External Assembly)&ensp;<button type="button" class="btn btn-primary btn-sm" v-on:click="boundObjectGet2Click()">Run</button>
                </div>
                <br><br>
                <div class="col-12">
                    <div class='table-responsive'>
                        <table id="boundObjectResult1" class='table'>
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Title</th>
                                    <th>Year</th>
                                    <th>Votes</th>
                                    <th>Rating</th>
                                    <th>Date</th>
                                    <th>RestfulAssembly</th>
                                </tr>
                            </thead>
                           <tbody tr v-for="item in boundObjectGet2Result">
                                <tr>
                                    <th>{{ item.Id }}</th>
                                    <th>{{ item.Title }}</th>
                                    <th>{{ item.Year }}</th>
                                    <th>{{ item.Votes }}</th>
                                    <th>{{ item.Rating }}</th>
                                    <th>{{ item.Date }}</th>
                                    <th>{{ item.RestfulAssembly }}</th>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
              </div>
            </b-tab>
            <b-tab title="Post">
               <div class="row">
                  <div class="col-12">
                        Route Path:&ensp;/demo/savemovies&ensp;(Restful Service in Local Assembly)&ensp;<button type="button" class="btn btn-primary btn-sm" v-on:click="boundObjectPostClick()">Run</button>
                    </div>
                    <br><br>
                    <div class="col-12">
                        <div>{{ boundObjectPostResult }}</div>
                    </div>
                </div>
            </b-tab>
        </b-tabs>

    </b-modal>
    <!-- End Bounds Object Modal -->

  </div>
</template>

<script src="./Demo.js"></script>

// ChromelyMvcAngularDemo/angularapp/src/app/demo/demo.component.ts
import { Component, OnInit, Output, NgZone } from '@angular/core';
import { Location } from '@angular/common';
import { IInfo } from '../services/info';
import { IMovie } from '../services/movie';
import { HttpService } from '../services/http.service';
import { RegisteredJsObjectService } from '../services/registered-js-object.service';

@Component({
  selector: 'app-demo',
  templateUrl: './demo.component.html',
  styleUrls: ['./demo.component.css']
})
export class DemoComponent implements OnInit {
  @Output() info: IInfo;

  @Output() movies: IMovie[];
  @Output() extenalMovies: IMovie[];
  @Output() postResult: string;

  @Output() httpMovies: IMovie[];
  @Output() httpExternalMovies: IMovie[];
  @Output() httpPostResult: string;

  postData: any;

  constructor(private _registeredJsObjectService: RegisteredJsObjectService,
    private _httpService: HttpService,
    private _zone: NgZone,
    private _location: Location) {

    this.info = <IInfo>{};

    // Initialize info
    this.info.Objective = 'Chromely Main Objectives';
    this.info.Platform = 'Platforms';
    this.info.Version = 'Version';
  }

  /*
  * Navigate back to home page
  */
  goBack(): void {
    this._location.back();
  }

  getInfo() {
    this._registeredJsObjectService.get<IInfo>('/info', null).subscribe(data => {
      this._zone.run(
        () => {
          this.info = data;
        })
    });
  }

  getMovies() {
    this._registeredJsObjectService.get<IMovie[]>('/demo/getmovies', null).subscribe(data => {
      this._zone.run(
        () => {
          this.movies = data;
        })
    });
  }


  saveMovies() {
    this._registeredJsObjectService.post<string>('/demo/savemovies', null, this.postData).subscribe(data => {
      this._zone.run(
        () => {
          this.postResult = data;
        })
    });
  }


  /*
     * Http Requests 
     */
  httpRequest(type: string, url: string): void {
    switch (type) {
      case "getlocal":
        this._httpService.getMovies(url).subscribe(data => {
          this.httpMovies = data;
        });
        break;
      case "getexternal":
        this._httpService.getMovies(url).subscribe(data => {
          this.httpExternalMovies = data;
        });
        break;
      case "post":
        this._httpService.postMovies(url, this.postData)
          .subscribe(result => {
            this.httpPostResult = result['Data'];
          });
        break;
      default:
        console.log('No valid http request found');
    }
  }

  ngOnInit() {
    this.postData = [
      {
        "Id": 1,
        "Title": "The Shawshank Redemption",
        "Year": 1994,
        "Votes": 678790,
        "Rating": 9.2
      },
      {
        "Id": 2,
        "Title": "The Godfather",
        "Year": 1972,
        "votes": 511495,
        "Rating": 9.2
      },
      {
        "Id": 3,
        "Title": "The Godfather: Part II",
        "Year": 1974,
        "Votes": 319352,
        "Rating": 9.0
      },
      {
        "Id": 4,
        "Title": "The Good, the Bad and the Ugly",
        "Year": 1966,
        "Votes": 213030,
        "Rating": 8.9
      },
      {
        "Id": 5,
        "Title": "My Fair Lady",
        "Year": 1964,
        "Votes": 533848,
        "Rating": 8.9
      },
      {
        "Id": 6,
        "Title": "12 Angry Men",
        "Year": 1957,
        "Votes": 164558,
        "Rating": 8.9
      }
    ]


    //this._httpService.getData().subscribe(data => {
    //    this.postData = data;
    //});

    //this._httpService.getInfo('http://chromely.com/info').subscribe(data => {
    //    this.info.objective = data['divObjective'];
    //    this.info.platform = data['divPlatform'];
    //    this.info.version = data['divVersion'];
    //});

    this.getInfo();
  }
}

<div>
  <div class="col-12">
    <div class="centerBlock">
      <span class="text-primary text-center"><h2>demo panel</h2></span>
      <p class="text-muted text-center">demo of chromely angular 2+ integration</p>
    </div>
  </div>

  <div class="col-12">
    <div>
      <button type="button" class="btn btn-link" (click)="goBack()">Back</button>
    </div>
    <div class="centerBlock">
      <button type="button" class="btn btn-light" data-toggle="modal" data-target="#boundJsObjectModal" style='margin: 5px;'>RegisterAsyncJsObject Demo</button>
      <button type="button" class="btn btn-light" data-toggle="modal" data-target="#httpModal" style='margin: 5px;'>Http Demo</button>
      <a href="https://github.com/mattkol/Chromely" class="btn btn-default" role="button" style='margin: 5px;'>more info</a>
    </div>
  </div>

  <br>

  <div id="infoPanel" class="col-12 centerBlock">

    <div>
      <div class="card-header card bg-primary text-white">Chromely Main objective</div>
      <div class="card-body"> {{ info.Objective }} </div>
    </div>
    <br>

    <div>
      <div class="card-header card bg-primary text-white">Platforms</div>
      <div class="card-body"> {{ info.Platform }}</div>
    </div>
    <br>

    <div>
      <div class="card-header card bg-primary text-white">Current CefSharp/Chromium Version</div>
      <div class="card-body">{{ info.Version }}</div>
    </div>
    <br>

  </div>

  <!-- The Modal RegisterAsyncJsObject Modal -->
  <div class="modal fade" id="boundJsObjectModal">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">

        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">.NET/JavaScript Integration Demo (RegisterAsyncJsObject)</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>

        <!-- Modal body -->
        <div class="modal-body">
          <!-- Nav pills -->
          <ul class="nav nav-pills" role="tablist">
            <li class="nav-item">
              <a class="nav-link active" data-toggle="pill" href="#sectionA">Get 1</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-toggle="pill" href="#sectionB">Get 2</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-toggle="pill" href="#sectionC">Post</a>
            </li>
          </ul>

          <!-- Tab panes -->
          <div class="tab-content">
            <div id="sectionA" class="container tab-pane active">
              <br>
              <div class="row">
                <div class="col-12">
                  Route Path:&ensp;/demo/movies &ensp; (Restful Service in Local Assembly)&ensp;<button type="button" class="btn btn-primary btn-sm" (click)="getMovies()">Run</button>
                </div>
                <br><br>
                <div class="col-12">
                  <div class='table-responsive'>
                    <table class='table'>
                      <thead>
                        <tr>
                          <th>Id</th>
                          <th>Title</th>
                          <th>Year</th>
                          <th>Votes</th>
                          <th>Rating</th>
                          <th>Date</th>
                          <th>RestfulAssembly</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr *ngFor='let movie of movies'>
                          <td>{{ movie.Id }}</td>
                          <td>{{ movie.Title }}</td>
                          <td>{{ movie.Year }}</td>
                          <td>{{ movie.Votes }}</td>
                          <td>{{ movie.Rating }}</td>
                          <td>{{ movie.Date }}</td>
                          <td>{{ movie.RestfulAssembly }}</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
            <div id="sectionB" class="container tab-pane fade">
              <br>
              <div class="row">
                <div class="col-12">
                  Route Path:&ensp;/external/movies &ensp;(Restful Service in External Assembly)&ensp;<button type="button" class="btn btn-primary btn-sm" (click)="getExternalMovies()">Run</button>
                </div>
                <br><br>
                <div class="col-12">
                  <div class='table-responsive'>
                    <table class='table'>
                      <thead>
                        <tr>
                          <th>Id</th>
                          <th>Title</th>
                          <th>Year</th>
                          <th>Votes</th>
                          <th>Rating</th>
                          <th>Date</th>
                          <th>RestfulAssembly</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr *ngFor='let movie of externalMovies'>
                          <td>{{ movie.Id }}</td>
                          <td>{{ movie.Title }}</td>
                          <td>{{ movie.Year }}</td>
                          <td>{{ movie.Votes }}</td>
                          <td>{{ movie.Rating }}</td>
                          <td>{{ movie.Date }}</td>
                          <td>{{ movie.RestfulAssembly }}</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
            <div id="sectionC" class="container tab-pane fade">
              <br>
              <div class="row">
                <div class="col-12">
                  Route Path:&ensp;/demo/savemovies&ensp;(Restful Service in Local Assembly)&ensp;<button type="button" class="btn btn-primary btn-sm" (click)="saveMovies()">Run</button>
                </div>
                <br><br>
                <div class="col-12">
                  <div>{{ postResult }}</div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
        </div>

      </div>
    </div>
  </div>

  <!-- The Modal Http Requests -->
  <div class="modal fade" id="httpModal">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">

        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">Http Requests</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>

        <!-- Modal body -->
        <div class="modal-body">
          <!-- Nav pills -->
          <ul class="nav nav-pills" role="tablist">
            <li class="nav-item">
              <a class="nav-link active" data-toggle="pill" href="#sectionI">Get 1</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-toggle="pill" href="#sectionJ">Get 2</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-toggle="pill" href="#sectionK">Post</a>
            </li>
          </ul>

          <!-- Tab panes -->
          <div class="tab-content">
            <div id="sectionI" class="container tab-pane active">
              <br>
              <div class="row">
                <div class="col-12">
                  Route Path:&ensp;/democontroller/movies &ensp; (Restful Service in Local Assembly&ensp;<button type="button" class="btn btn-primary btn-sm" (click)="httpRequest('getlocal', 'http://chromely.com/democontroller/movies')">Run</button>
                </div>
                <br><br>
                <div class="col-12">
                  <div class='table-responsive'>
                    <table class='table'>
                      <thead>
                        <tr>
                          <th>Id</th>
                          <th>Title</th>
                          <th>Year</th>
                          <th>Votes</th>
                          <th>Rating</th>
                          <th>Date</th>
                          <th>RestfulAssembly</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr *ngFor='let movie of httpMovies'>
                          <td>{{ movie.Id }}</td>
                          <td>{{ movie.Title }}</td>
                          <td>{{ movie.Year }}</td>
                          <td>{{ movie.Votes }}</td>
                          <td>{{ movie.Rating }}</td>
                          <td>{{ movie.Date }}</td>
                          <td>{{ movie.RestfulAssembly }}</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
            <div id="sectionJ" class="container tab-pane fade">
              <br>
              <div class="row">
                <div class="col-12">
                  Route Path:&ensp;/externalcontroller/movies &ensp; (Restful Service in External Assembly)&ensp;<button type="button" class="btn btn-primary btn-sm" (click)="httpRequest('getexternal', 'http://chromely.com/externalcontroller/movies')">Run</button>
                </div>
                <br><br>
                <div class="col-12">
                  <div class='table-responsive'>
                    <table class='table'>
                      <thead>
                        <tr>
                          <th>Id</th>
                          <th>Title</th>
                          <th>Year</th>
                          <th>Votes</th>
                          <th>Rating</th>
                          <th>Date</th>
                          <th>RestfulAssembly</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr *ngFor='let movie of httpExternalMovies'>
                          <td>{{ movie.Id }}</td>
                          <td>{{ movie.Title }}</td>
                          <td>{{ movie.Year }}</td>
                          <td>{{ movie.Votes }}</td>
                          <td>{{ movie.Rating }}</td>
                          <td>{{ movie.Date }}</td>
                          <td>{{ movie.RestfulAssembly }}</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
            <div id="sectionK" class="container tab-pane fade">
              <br>
              <div class="row">
                <div class="col-12">
                  Route Path:&ensp;/democontroller/savemovies &ensp;(Restful Service in Local Assembly)&ensp;<button type="button" class="btn btn-primary btn-sm" (click)="httpRequest('post', 'http://chromely.com/democontroller/savemovies')">Run</button>
                </div>
                <br><br>
                <div class="col-12">
                  <div>{{ postHttpResult }}</div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
        </div>

      </div>
    </div>
  </div>

</div>
